### ISSUE TITLE
Typo in Organigram

### ISSUE THREAD

**Issue by Gian-z** [swissictedu/ipa-template#3]
The organisation.tex file contains a typo "Arbeits" at 7:73

**Comment by Gian-z** [comment]
addition:
5:39 "Abteiltung"

**Comment by openscript** [comment]
Ciao Gian! :) Thank you for raising this. Can you create a PR for this matter?

**Comment by Gian-z** [comment]
@openscript done ^^

**Comment by openscript** [comment]
@Gian-z Thx!
